### ISSUE TITLE
Simplify configuration - get rid of "releasing.build.branch"

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#101]
### Problem

We should be able to to simplify release configuration and get rid of "releasing.build.branch" completely:

```Gradle
releasing {
  //we should be able to get rid of the below and configure automatically:
  build.branch = System.getenv("TRAVIS_BRANCH")
}
```

It is super annoying that I have to configure TRAVIS_BRANCH env variable even for local testing or releasing from local (I'm not Travis!). Fixing it will make the tools easier to use today, and easier to integrate with other tools in the future.

### Workflow

1. travisReleasePrepare task ensures that TRAVIS_BRANCH is checked out.
2. in other workflows (non-travis), for example local testing, deployment from local, we don’t read nor require the TRAVIS_BRANCH property at all.

### Suggested implementation

See the suggested starting point design at: https://github.com/mockito/mockito-release-tools/pull/102

**Comment by szczepiq** [comment]
@epeee, this is related to your previous neat work, making the release configuration even simpler. Do you want to take a stab at it? :)

**Comment by epeee** [comment]
@szczepiq yes, I will do so tomorrow.
