### ISSUE TITLE
Release notes use visual badge for downloads

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#117]
### Goal

When release notes are cleaner and prettier they manifest more credibility and can attract more adopters of our tools. We need lots of users to succeed!

### Implementation

Currently, the [release notes](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md) have bare link to the publication repository. It would be great if it had a download badge just like we have it on [Mockito main page](https://github.com/mockito/mockito/blob/release/2.x/README.md).

### Coding!

- The publication repository is currently rendered in release notes via [DetailedFormatter](https://github.com/mockito/mockito-release-tools/blob/master/src/main/groovy/org/mockito/release/notes/format/DetailedFormatter.java#L59) class.
- The repository link markdown is constructed [here](https://github.com/mockito/mockito-release-tools/blob/2572ea3bf41cdce4d3b30693826e6928c1150c62/src/main/groovy/org/mockito/release/internal/gradle/util/BintrayUtil.java#L19).
- Example badges: [![Bintray](https://img.shields.io/badge/Bintray-2.8.31-green.svg)](https://bintray.com/mockito/maven/mockito-development/2.8.31) [![Maven Central](https://img.shields.io/maven-central/v/org.mockito/mockito-core.svg)](https://maven-badges.herokuapp.com/maven-central/org.mockito/mockito-core)

### Testing

- e2e testing with example project - update previous version in the version.properties file (use some lower version) and run ```./gradlew previewReleaseNotes```

### Full example

Current way of presenting release in notes:

**2.8.31 (2017-05-22)** - [1 commit](https://github.com/mockito/mockito/compare/v2.8.30...v2.8.31) by [Rafael Winterhalter](http://github.com/raphw) - published to [maven/mockito-development](https://bintray.com/mockito/maven/mockito-development)

Desired way of presenting release in notes:

**2.8.31 (2017-05-22)** - [1 commit](https://github.com/mockito/mockito/compare/v2.8.30...v2.8.31) by [Rafael Winterhalter](http://github.com/raphw) -  [![Download](https://img.shields.io/badge/Bintray-2.8.31-green.svg)](https://bintray.com/mockito/maven/mockito-development/2.8.31)

**Comment by szczepiq** [comment]
@NagRock, want to take a stab at it? Bigger features await... :)

**Comment by NagRock** [comment]
@szczepiq Ok, but first I will finish `serializers` and probably will have some questions before I will start with this issue. But you can assign me :)

**Comment by NagRock** [comment]
Bintray badge added in https://github.com/mockito/mockito-release-tools/pull/176
