### ISSUE TITLE
Running example tasks

### ISSUE THREAD

**Issue by NagRock** [mockito/mockito-release-tools#139]
Hi, I have problem with running any of example tasks from readme.

I've cloned mockito-release-tools-examples

`run './gradlew testRelease'` - resulting with: `Missing 'bintray.key' value. Please configure Bintray extension or export 'BINTRAY_API_KEY' env variable.`

`run './gradlew testNotableRelease'` - resulting with: `Task 'testNotableRelease' not found in root project 'example-release'.`

`run './gradlew performRelease -m' (-m means dry run)` - resulting with: `Missing 'bintray.key' value. Please configure Bintray extension or export 'BINTRAY_API_KEY' env variable.`

`run './gradlew previewReleaseNotes'` - resulting with: `FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':previewReleaseNotes'. > Can't deserialize JSON: `

Can you give some more informations about running examples?

Thanks!

**Comment by mstachniuk** [comment]
Check our example project: https://github.com/mockito/mockito-release-tools-example

We are working on better documentation, but the code first:-)

**Comment by NagRock** [comment]
I've run all described task on this project.

**Comment by mstachniuk** [comment]
Ohh ok I see now you are using this project already. We are working on fixing problems... Maybe could you help us?

**Comment by NagRock** [comment]
I want to but without working any example task I can't even try to start :)

**Comment by szczepiq** [comment]
Hej @NagRock, welcome!!!

Sorry for the hiccups, we are not 1.0 yet ;)

To get you started with, this should work in the example project:

```
./gradlew clean previewReleaseNotes
./gradlew build testRelease -x bintrayUpload -x gitPush
```

Thank you for reporting this! We surely need clear instructions in the readme how to get started with the sample project.

**Comment by NagRock** [comment]
Ok the problem is with `build/release-tools/all-contributors.json` file. It does not exists on my build directory. I see that it should be created by `ContributorsPlugin` but when I run `./gradlew fetchAllContributors` I'm just getting info that this task is skipped: 
`:fetchAllContributors SKIPPED`

When I created `all-contributors.json` file manually with empty array `previewReleaseNotes` task worked :)

Maybe you know why `fetchAllContributors` task is always skipped?

**Comment by NagRock** [comment]
Oh now I read https://github.com/mockito/mockito-release-tools/issues/120 and all is clear.

**Comment by szczepiq** [comment]
>When I created all-contributors.json file manually with empty array previewReleaseNotes task worked :)
>Maybe you know why fetchAllContributors task is always skipped?

Looks like a bug. Looks like my bug! :) That's not how it supposed to work. It should be seamless, as described in #120. I suspect that the task is skipped because the [contributors list](https://github.com/mockito/mockito-release-tools-example/blob/master/gradle/release.gradle#L23) is supplied by the user. However, some other task further down the chain forcefully attempts to deserialize the file. It should not do it given we already have the list supplied by the user.

Hope that helps! BTW. Do you want to get involved in the project?

**Comment by NagRock** [comment]
Yes, I'm trying to "get into code" currently, but don't know if I got enough skills for so serious project :)

**Comment by szczepiq** [comment]
>Yes, I'm trying to "get into code" currently, but don't know if I got enough skills for so serious project :)

Great! We need help to push the project to 1.0 and then, to conquer the world! 🗡 When I have some time I will give some pointers on what gaps we currently have that you could try to tackle :)

**Comment by szczepiq** [comment]
I will close this for now. Contributing file explains how to do testing!
