### ISSUE TITLE
Enable end-to-end release notes generation for testing

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#15]
External contributors don't know how to end-to-end test the release notes generation. See this excellent pull request:  #12 (the user is asking how to make e2e test). Without this, it is hard to approve and merge PRs with confidence.

At very least we need a clear documentation how to do that with Mockito. Ideally, we have a test bed project for that on GitHub.

**Comment by szczepiq** [comment]
Opened PR to mockito repository: https://github.com/mockito/mockito/pull/968

**Comment by mstachniuk** [comment]
One example e2e test is enough. A big documentation how to do it, it's not necessary.
