### ISSUE TITLE
Commit skipping logic is hardcoded and yields subtle bugs in release notes content

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#155]
## Problem

For generating release notes with number of commits and contributors, we skip "automated" commits. It is an important feature because the number of commits is off if we consider commits made by release automation. The automated skip message is configurable by the user and Mockito project [uses it](https://github.com/mockito/mockito/blob/release/2.x/gradle/root/release.gradle#L30). However, the implementation of shipkit is hardcoded to ignore commits with [ci skip] - [see the code](https://github.com/mockito/mockito-release-tools/blob/822c8f8a06c5c82e924dc6ba95998af86450d2f6/src/main/groovy/org/mockito/release/notes/vcs/IgnoreCiSkip.java#L17).

Even though the skip message is hardcoded, the recent Mockito release notes seems to calculate commits correctly. Why? :)

## Suggested change

For the time being, let's ignore all commits with "[ci skip]" and also all commits that contain releasing.git.commitMessagePostfix. Code hints:

- Code that contains hardcoded ["[ci skip]"](https://github.com/mockito/mockito-release-tools/blob/822c8f8a06c5c82e924dc6ba95998af86450d2f6/src/main/groovy/org/mockito/release/notes/vcs/IgnoreCiSkip.java#L17)
- Code that contains [commitMessagePostfix configuration](https://github.com/mockito/mockito-release-tools/blob/3abab2fd4de535f4111a838ee35e04ee95c37a0e/gradle/release.gradle#L12)

**Comment by szczepiq** [comment]
@NagRock, do you want to take a stab at it? :)

**Comment by NagRock** [comment]
Yea! You can assign me
