### ISSUE TITLE
Date placement in release notes

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#171]
Currently the date is presented in following way in the release notes ([full example](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md)):

**2.8.31** - [1 commit](https://github.com/mockito/mockito/compare/v2.8.30...v2.8.31) by [Rafael Winterhalter](http://github.com/raphw) - *2017-05-22* - published to [maven/mockito-development](https://bintray.com/mockito/maven/mockito-development)

We should present it closer to the version, in front of the line:

**2.8.31 (2017-05-22)** - [1 commit](https://github.com/mockito/mockito/compare/v2.8.30...v2.8.31) by [Rafael Winterhalter](http://github.com/raphw) - published to [maven/mockito-development](https://bintray.com/mockito/maven/mockito-development)

### Implementation

- This is where we render the version in the release notes [in DetailedFormatter class](https://github.com/mockito/mockito-release-tools/blob/master/src/main/groovy/org/mockito/release/notes/format/DetailedFormatter.java#L41)
- This is where we currently render date [in DetailedFormatter](https://github.com/mockito/mockito-release-tools/blob/master/src/main/groovy/org/mockito/release/notes/format/DetailedFormatter.java#L59)

### Testing

e2e testing with example project - update previous version in the version.properties file (use some lower version) and run ./gradlew previewReleaseNotes

**Comment by szczepiq** [comment]
@epeee, what do you think about this ticket? It's not a bit time investment but it would help you get into the project!

**Comment by epeee** [comment]
@szczepiq sounds good.
