### ISSUE TITLE
Rename configuration extension 'releasing' -> 'shipkit'

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#172]
### Problem & plan

In order to fully embrace the new name of the project, we need to rename 'releasing' -> 'shipkit'. Steps:
 - [x] - update code and tests
 - [x] - submit pull request to mockito-release-tools-example
 - [x] - submit pull request to mockito

### Details

Current API: the release is configured via 'releasing' extension in shipkit.gradle file:

```
releasing {
    gitHub.repository = "mockito/mockito"
    gitHub.readOnlyAuthToken = "a0a4c0f41c200f7c653323014d6a72a127764e17"
    ...
}
```

Expected API: the Gradle DSL extension should be called 'shipkit':

```
shipkit {
    gitHub.repository = "mockito/mockito"
    gitHub.readOnlyAuthToken = "a0a4c0f41c200f7c653323014d6a72a127764e17"
    ...
}
```

**Comment by szczepiq** [comment]
I think that @NagRock has implemented most of that already, so I'm assigning the ticket :)

**Comment by NagRock** [comment]
https://github.com/mockito/mockito-release-tools-example/pull/42
https://github.com/mockito/mockito/pull/1104
