### ISSUE TITLE
Clean up public and internal API package distinction

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#178]
### Problem

We need clean separation of public and internal API for Shipkit 1.0. We need smaller public API because it helps us develop new API carefully while keeping compatibility.

### Suggested plan

Current package structure:

```
org.mockito.release.exec - process runner
org.mockito.release.gradle - public Gradle tasks, and public Gradle extensions
org.mockito.release.internal - all internal
org.mockito.release.notes - release notes
org.mockito.release.version - versioning
```

Desired package structure - for 1.0 we will only expose Gradle tasks as public types and Gradle extensions. Everything else will be internal because we want to limit the scope of 1.0 public API. Later on, we can start exposing more public APIs or even a library that can be used without Gradle.

```
org.shipkit.gradle - public Gradle tasks, and public Gradle extensions
org.shipkit.internal - all internal
```

### Suggested implementation

 - [x] - rename "org.mockito.release.gradle" into "org.shipkit.gradle"
 - [ ] - move all other packages and classes under "org.shipkit.internal"

Example:

```
org.mockito.release.exec -> org.shipkit.internal.exec
```

**Comment by epeee** [comment]
I can work on this one once the ABTesting topic is finished. 
Finally, I do have more time for OSS again.

**Comment by epeee** [comment]
I can start working on this one tomorrow if that's ok for you.

**Comment by NagRock** [comment]
@szczepiq I think this issue will be partly invalid when https://github.com/mockito/mockito-release-tools/pull/188 will be merged?

**Comment by epeee** [comment]
@NagRock thx for pointing that out, although the 2nd point is still valid.

**Comment by szczepiq** [comment]
That's correct! Thank you for working on this. It's nice to see that we're making progress on cleaning up the public api and renames.

**Comment by szczepiq** [comment]
Accidentally closed :)
