### ISSUE TITLE
Clean up shipkit Gradle plugin names

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#179]
Before 1.0 release we need to clean up Gradle plugin names and some behavior, too. See [Shipkit Gradle Plugin Reference](https://github.com/mockito/mockito-release-tools/wiki/Shipkit-Gradle-Plugin-Reference).

### Java plugin clean up

- [ ] - rename "org.mockito.release-tools.continuous-delivery" -> "org.shipkit.java"
- [x] - rename "org.mockito.release-tools.java-library" -> "org.shipkit.java-library"
- [ ] - change "org.shipkit.java" plugin so that it automatically applies "org.shipkit.java-library" plugin for all java subprojects. This will be helpful because our clients will not have to apply "org.shipkit.java-library" explicitly. Suggested implementation, in "org.shipkit.java" plugin (pseudo code :):

```groovy
allprojects { subproject -> 
  subproject.plugins.withId("java") { 
    apply plugin: "org.shipkit.java-library" 
  }
}
```
- [ ] - update mockito-release-tools-example project and remove the use of "org.mockito.release-tools.java-library"

**Comment by mstachniuk** [comment]
ad. 3. Is it safe? What if in some library one subproject is native C++ project?

**Comment by NagRock** [comment]
ad. 2. already done in https://github.com/mockito/mockito-release-tools/pull/188
