### ISSUE TITLE
Missing contributors in the release notes file

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#184]
In recent release of Mockito, @epeee was not automatically included in the release notes and I had to manually update the release notes file ([see commit](https://github.com/mockito/mockito/commit/f719356a63a5d9b5920e0308756149880131512b)).

### Steps to reproduce

I haven't tested those steps so pardon if something does not work :)

- clone Mockito repo
- bump tools to latest version (hopefully everything works, we're still not 1.0 yet :)
- update the previousVersion in the version.properties file to be something prior to @epeee changes
- run ```./gradlew previewReleaseNotes```

### Implementation

For testing / development guidelines, please refer to our CONTRIBUTING.md

**Comment by szczepiq** [comment]
@epeee, is this something you want to look at? :)

**Comment by epeee** [comment]
@szczepiq yes, I will do so.

**Comment by mstachniuk** [comment]
It was solved before by https://github.com/mockito/mockito-release-tools/pull/168 but not merged yet :-(
