### ISSUE TITLE
Make applying java-library plugin conditional on a property

### ISSUE THREAD

**Issue by wwilk** [mockito/mockito-release-tools#200]
Currently we apply java-library on each subproject with java plugin already applied. It should be possible to disable this mechanism. As suggested by @szczepiq we can add a property "shipkit.releaseAllJavaModules" to ReleaseConfiguration. By default this property should be true and in this case java-library would be applied automatically.

**Comment by szczepiq** [comment]
Thank you for creating the ticket! We can polish it a bit and mark with 'please-contribute'.
