### ISSUE TITLE
Expose “version” and “tagPrefix” as task properties

### ISSUE THREAD

**Issue by epeee** [mockito/mockito-release-tools#201]
### Why?
Currently, the task which generates the release notes does not declare `version` and `tagPrefix` as input. Therefore it can be harder to use for advanced use cases.
### How?
 - expose “version” and “tagPrefix” properties as task properties marked with `@input`
 - configure default values via release notes plugin.

**Comment by szczepiq** [comment]
Perfect. Thank you for creating the ticket with clean description!
