### ISSUE TITLE
Automatically include contributors in pom.xml file

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#36]
## Use case

In order to reward contributors and further motivate for more high quality contributions it would be great to list contributors in the [relevant section of pom.xml](http://maven.apache.org/pom.html#Contributors) file. As of 3/18/17 generation of pom.xml logic is a part of Mockito project automation and it is not generic enough to be part of mockito release tools.

## Design

This idea needs to be fleshed out further. An example technical design that we could try implementing:

- currently every contribution is explicitly mentioned in the release notes but it should also automatically include the contributor in the pom.xml of every future version of mockito.
- see [TODO with brainstorming ideas](https://github.com/mockito/mockito-release-tools/blob/master/src/main/groovy/org/mockito/release/internal/gradle/pom/DefaultPomPlugin.java#L17) in the code
- need a way to generate pom.xml template with contributor information for past releases so that we include contributors of the past (we can simplify and ignore contributors of 1.x version).
- Maven pom reference for "contributors" section: http://maven.apache.org/pom.html#Contributors

## Action plan

This is a great ticket for external contribution! Please consider helping out! 

- The next action is to think through the design, perhaps do some prototyping and comment back on this ticket with the technical design we actually want to execute. The previous design note was my quicky brainstorming.
- Submit PR! (@mstachniuk, wdyt?)

**Comment by mstachniuk** [comment]
I think it can be done without any pom.xml template - it will be hard to keep template and pom.xml in sync. I will look more deeply on it in April.

**Comment by szczepiq** [comment]
I've created initial pom plugin. Added a TODO to the code with [some examples](https://github.com/mockito/mockito-release-tools/blob/master/src/main/groovy/org/mockito/release/internal/gradle/pom/DefaultPomPlugin.java#L17) how to approach the problem :)

**Comment by mstachniuk** [comment]
Design question
I fought about how to solve this problem. `GitHubContributorsProvider.mapContributorsToGitHubUser(...)` always ask only for contributors between two commits (usually last released version and HEAD). My first idea was to call this method inside `PomCustomizer.customizePom(...)`, but then only last contributors will be added to the pom.xml (and hardcoded in `gradle/release.gradle`).

In my opinion it's better to update in some previous step (before `generatePomFileForJavaLibraryPublication`) a property `ext.pom_contributors` in `gradle/release.gradle` and add new contributors to the list. Then we need to adjust logic in `PomCustomizer.customizePom(...)` a little bit (to handle more info about contributors) and continous-delivery-drone will commit this file together with release-notes. In this approach we reduce a number of requests to github.com, speed up a build and are sure that we don't skip anybody in pom.

@szczepiq WDYT?

**Comment by szczepiq** [comment]
Let's optimize for:
 - least amount of requests to GitHub
 - minimum overhead to the build time

We have a couple of options:
 - we just maintain the mapping in a file, it would be manually maintained
 - we add a discrete step (task) that gets the data before we update pom (this is what you're suggesting, right?)
 - do some smart caching if possible, commits pushed to main dev branches don't change :)

I've started to use latest version of mockito release tools in mockito and noticed that the generation of notable release notes adds overhead due to getting the user mappings for [each notable version](https://github.com/mockito/mockito-release-tools/blob/master/src/main/groovy/org/mockito/release/notes/generator/DefaultReleaseNotesGenerator.java#L60). For the time being I'll simplify it and avoid requesting user mappings for notable release notes. They don't need it because the notable notes don't have authors (for now, we can change it if we see fit).

Thank you for working on this!!!
