### ISSUE TITLE
Make updateNotableReleaseNotes task incremental

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#54]
In order to make the local builds faster (and testing faster!) let's make updateNotableReleaseNotes task incremental (NotableReleaseNotesGeneratorTask).

### Suggested design

NotableReleaseNotesGeneratorTask class currently fetches release notes data from git / GitHub every time it runs. Instead, let's split the logic into discrete steps to and leverage incremental build. The first step of NotableReleaseNotesGeneratorTask currently is to fetch Collection<ReleaseNotesData> from generator object. Let's push that logic to a separate Gradle task, "fetchNotableNotes" (type: NotableNotesFetcherTask). The new new task will:

- fetch the data and construct Collection<ReleaseNotesData>
- save it to the file (we can use Java serialization for now but we really want something nicer, like JSON)
- declare correct inputs and outputs so that it is incremental, inputs are various properties currently available on NotesGeneration type. Output is a file.

The existing NotableReleaseNotesGeneratorTask needs to:
 - load release notes data (Collection<ReleaseNotesData>) from the file
 - depend on "fetchNotableNotes" task

### Testing and prototyping

- see [Mockito Release Tools readme](https://github.com/mockito/mockito-release-tools#testing) for info on testing
- run "./gradlew updateNotableReleaseNotes" in example project

**Comment by wwilk** [comment]
The main part of the task (making updateNotableReleaseNotes incremental) is done, so I'm closing the task and moving improvements in serialization (JSON instead of Java serialization) to a new issue.
