### ISSUE TITLE
Applying the plugin on project without 'version.properties' file yields stack trace

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#70]
Applying one of our plugins, "org.mockito.mockito-release-tools.versioning" or "org.mockito.mockito-release-tools.continuous-delivery" plugin in a project that does not have 'version.properties' file yields nasty stack trace. We need to handle this use case gracefully. Example solutions:

- fail with decent exception telling the user what to do
- generate the file for the user and log information that the file should be checked-in
- create some sort of bootstrap task that will setup all necessary files for getting continuos delivery set up for a project

**Comment by wwilk** [comment]
Done
