### ISSUE TITLE
fetchNotableReleaseNotes fails ungracefully when incorrect tag is supplied

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#71]
fetchNotableReleaseNotes task fails with below stack trace when one of the input tags is missing. Let's have more graceful handling of this scenario, the exception message should indicate a potential problem and suggest a resolution.

Stack trace:

```
:fetchNotableReleaseNotes FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fetchNotableReleaseNotes'.
> Problems parsing date: [fatal: ambiguous argument 'v2.7.0': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]']. Required format is: [yyyy-MM-dd HH:mm:ss Z].

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by szczepiq** [comment]
@wwilk, something you can take look?

**Comment by mstachniuk** [comment]
This tag is missing in Mockito project, but it's in version.properties

12 kwi 2017 7:17 AM "Szczepan Faber" <notifications@github.com> napisał(a):

**Comment by szczepiq** [comment]
@wwilk, is this completed? Can you close if you believe it's don? Thank you! :)

**Comment by wwilk** [comment]
Yes, it's completed. Closing it!
