### ISSUE TITLE
New extension object for configuring the plugins

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#76]
Let's start using an extension object to configure the plugins. This is more idiomatic approach used by Gradle plugins and we should adhere to standards as much as possible. Here's how the configuration would look in Mockito. Please give feedback:

```gradle
//minimal
releasing {
    github {
        repository = "mockito/mockito"
        writeAuthUser = "szczepiq"
        readOnlyAuthToken = "a0a4c0f41c200f7c653323014d6a72a127764e17"
    }
}

//fully configured
releasing {
    github {
        repository = "mockito/mockito"
        writeAuthUser = "szczepiq"
        writeAuthToken = System.getenv("GH_WRITE_TOKEN")
        readOnlyAuthToken = "a0a4c0f41c200f7c653323014d6a72a127764e17"
    }
    releaseNotes {
        file = "doc/release-notes/official.md"
        notableFile = "doc/release-notes/notable.md"
        labelMapping = [
            '1.* incompatible': 'Incompatible changes with previous major version (v1.x)',
            'java-9': "Java 9 support",
            'java-8': "Java 8 support",
            'new feature': "New features",
            'BDD': 'Behavior-Driven Development support',
            'bug': "Bugfixes",
            'enhancement': "Enhancements",
            'android': "Android support",
            'docs': 'Documentation'
        ]
    }
    git {
        genericUser = "Mockito Release Tools"
        genericEmail = "<mockito.release.tools@gmail.com>"
        releasableBranchRegex = "master|release/.+"  // matches 'master', 'release/2.x', 'release/3.x', etc.
        branch = System.getenv("TRAVIS_BRANCH")
    }
    team {
        developers = ['szczepiq:Szczepan Faber', 'bric3:Brice Dutheil', 'raphw:Rafael Winterhalter', 'TimvdLippe:Tim van der Lippe']
        contributors = []
    }
}
```

**Comment by mstachniuk** [comment]
It looks better then current configuration. 
For me `git.user` and `git.email` might be confused for what it is.
Maybe instead of `library` it should be `general` or `info` or `extras`?
What about bintray/maven upload repo settings?

**Comment by szpak** [comment]
I also found it handy to use one extension (usually with multiple other classes used under the hood to map subclosures (`github`, `releaseNotes`) to keep code in a good shape), however there could be two topics to address:
1. (mentioned already by @mstachniuk) - a configuration of 3rd party plugins applied by `mockito-release-tools`. I found it somehow problematic to provide my own configuration (here as `release/bintray`) for Nexus/Bintray plugin. In a simple scenario you could initialize original `bintray` extension with default values (leave it as is), allow people to set custom properties in your subextension and in `afterEvaluate` override selected properties in the `bintray` extension. However, people can try to configure it using external `bintray {}` configuration block (only there or in addition to your configuration closure). In that case in `afterEvaluate` your are not sure which properties in `bintray` extension should be overridden by (default or changed by an user) properties in your `release/bintray` configuration block. Do you have a good idea how to deal with it?
2. I personally planned to reuse just the release notes plugin alone to generate changelog for my own release mechanism. In the current version it would be possible to just apply that plugin and provide a configuration closure. Would it be still possible after incorporation of it into one big extension closure?

P.S. I agree with @mstachniuk  that `library` can be confusing. Not sure however, what would be better.

**Comment by szczepiq** [comment]
Fantastic feedback, thanks a lot guys!!!

>For me git.user and git.email might be confused for what it is.

I was hoping that the setting value clear up what the methods are :) We could call them: git.genericUser / git.automaticUser / git.releaseAutomationUser / git.toolingUser. If there are no other votes, I'll rename it to 'genericUser' and 'genericEmail'.

>What about bintray/maven upload repo settings?

I'd rather avoid wrapping over the original Bintray extension. It will be awkward to maintain and problematic when some stuff is configured in our extension and some in Bintray extension. I have similar experiences as @szpak :)

So, the release tools extension will not provide any configuration for bintray.

>P.S. I agree with @mstachniuk that library can be confusing. Not sure however, what would be better.

Ok, thanks for feedback! More options: 'pom', 'team'.

**Comment by szczepiq** [comment]
@szpak 

>I personally planned to reuse just the release notes plugin alone to generate changelog for my own release mechanism. In the current version it would be possible to just apply that plugin and provide a configuration closure. Would it be still possible after incorporation of it into one big extension closure?

Yes, it will be possible, you can do:

```Groovy
apply plugin: "org.mockito.mockito-release-tools:release-notes"

releasing {
  releaseNotes {
    ...
  }
}
```

Alternatively, you can just use the custom tasks and not apply any plugin. We will have all task neatly documented and part of the public API.

In general, we would really like to work with your use case to make the tools generic enough to handle neatly!

**Comment by szczepiq** [comment]
Started making progress on this at #77

**Comment by mstachniuk** [comment]
`git.user` and `git.email` properties are used by Continuous Integration server / Travis-CI to make git operations. Maybe we should wrap it in `ci`, `ciServer`, `buildServer`, or change `git` to `ciGit`, `gitOnCi` `gitOnBuildServer` or similar? 
I think this settings should be optional, because on some CI servers (e.g. internal in house) it can be preconfigured.

**Comment by szczepiq** [comment]
>I think this settings should be optional, because on some CI servers (e.g. internal in house) it can be preconfigured

Good idea. I will add "minimum" extension and "full" extension so that folks can see the difference.

**Comment by szpak** [comment]
@szczepiq Regarding my concerns related to a big extension I was worrying that using only `release-notes` will not be possible due to a lack of other classes. However, I forgot that they are sill in one big jar (will one on a claspath) and I just limit an apply operation, so it should be fine.

**Comment by szczepiq** [comment]
Ok. They are a part of single jar now. There is no big reason to split them at the moment. It will happen at some point I think if users find the subcomponents useful on its own. We should have some driving use cases then. Perhaps some use cases from you!

**Comment by szczepiq** [comment]
Merged.
