### ISSUE TITLE
Release tools project dogfoods versioning plugin

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#87]
### Problem

Release tools project currently defines its version in root "build.gradle" file and it is problematic because:
 - it is not bumped automatically with the release
 - it triggers merge conflicts in "build.gradle" file instead of merge conflicts in a simpler 'version.properties' file.

### Suggested implementation

1. Have the release tools project consume the 'org.mockito.release-tools.versioning' plugin from the previously released version of tools.
2. Update the travisRelease task so that when we release we bump version automatically.
3. Bonus - we should configure versioning plugin in 'pluginBundle' section of 'build.gradle' file. See the documentation of Gradle plugins portal: https://plugins.gradle.org/docs/publish-plugin.

### Future

We should make the release tools plugin actually consume the entire continuous delivery plugin. We can get there step by step.

**Comment by szczepiq** [comment]
@wwilk, do you want to take a stab at it? It's related to the version fix you've done earlier and might be good to get you immersed in the project more!

**Comment by wwilk** [comment]
Sure! I will work on it soon.

**Comment by szczepiq** [comment]
Fiendly ping :) It bothers me that we always have to remember to bump the version of tools when publishing :/

**Comment by szczepiq** [comment]
I'm thinking that we should make the plunge and start dogfooding release notes generation in this project, too. Let's rock! What do you think? Or perhaps new plugin like "GradlePluginReleasingPlugin"? :D

**Comment by wwilk** [comment]
Sure, we can do that!
