### ISSUE TITLE
Use JSON serialization/deserialization in ReleaseNotesSerializer

### ISSUE THREAD

**Issue by wwilk** [mockito/mockito-release-tools#91]
We want to use JSON format instead of Java serialization one for storing release notes. It would be probably best to use json-simple for this, since it's already a dependency.

**Comment by szczepiq** [comment]
I removed the please contribute label for now if that's ok =). I completely agree that the feature needs to be implemented, though! I penned down the [criteria for "please contribute!"](https://github.com/mockito/mockito-release-tools/blob/master/README.md#getting-contributions) label in the README.md.

**Comment by NagRock** [comment]
Don't you think that `Serializer` class should not write serialized data to file? In my opinion `Serializer` class should only return `JSONString` and some `FileWriter` could be used to store serialized data into file.
Why? Because now we can't reuse `AllContributorsSerializer` to implement `ReleaseNotesSerializer` as `ContributionSet` is part of `ReleaseNotesData`.

**Comment by NagRock** [comment]
@szczepiq it's not done yet. I just made a little part. Think that You should reopen it and I can finish this task completely. Just want to know if this is good way before doing all things.

**Comment by NagRock** [comment]
Hi again, I want to ask if there is any reason why we using JSON simple library instead of Jackson or something else?
We got to manually format object to strings with this lib, and deserialization of complex structures with collections is getting really complicated.

**Comment by szczepiq** [comment]
Hey! Nice catch! Please suggest an alternative library. You can kick off the discussion here, on our slack or on the mailing list.

One of our goals is to keep the dependencies of library as narrow and as simple as possible to avoid pushing down version conflicts onto our clients (e.g. the cost of reuse...). I suspect that we didn't choose some other library for those reasons :)

**Comment by NagRock** [comment]
I think that Jacskon is a really good option. We can use `ObjectMapper` to convert to JSON and back to Java object with given class:
```ObjectMapper mapper = new ObjectMapper();
User user = new User();

//Object to JSON in file
mapper.writeValue(new File("c:\\user.json"), user);
```

And back to Java object:

```bjectMapper mapper = new ObjectMapper();
String jsonInString = "{'name' : 'mkyong'}";

//JSON from file to Object
User user = mapper.readValue(new File("c:\\user.json"), User.class);
```

Without any casting as in `simple JSON` or reading field by field. `Simple JSON` returns `JsonObject`, `JsonArray` etc. instead of typed object and we got to do many things manually. I think its good lib for small project when we want to read one json file.

**Comment by mstachniuk** [comment]
Dependencies of Jackson:

```
+--- com.fasterxml.jackson.core:jackson-databind:2.8.8.1
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.8.0
|    \--- com.fasterxml.jackson.core:jackson-core:2.8.8
```

Dependencies of json-simple:

```
+--- com.github.cliftonlabs:json-simple:2.1.2
```

I don't have strong preferences but with Jackson the life is simpler :) We need only remember to use `2.6.6 (05-Apr-2016)` version for Java 1.6 compatibility: https://github.com/FasterXML/jackson-databind/blob/master/release-notes/VERSION

**Comment by NagRock** [comment]
@szczepiq whats your opinion? Should I move to Jackson within this issue and replace Simple Json in app?

**Comment by wwilk** [comment]
We had this discussion about a month ago, and decided against any reflection-based library. One reason is that most of them are much heavier, not only due to transitive dependencies but also the size of libraries themselves (jackson-databind 1.2 MB vs json-simple 17 KB). I'm not sure if that will matter in the long run, but for now we don't have much dependencies and it would be good to keep it that way. Additionally @NagRock serialization/deserialization with jackson is not that straightforward if we want to serialize to file and then deserialize, like with release notes. Since the model is mostly based on interfaces we would have to use some kind of jackson inheritance to implement it.

**Comment by NagRock** [comment]
So you suggest to continue working on this with json simple? Im ok with that but it is a little bit tedious work.

**Comment by NagRock** [comment]
Ok, now it can be closed.
